openapi: 3.0.1
info:
  title: Simple User API
  description: API simples para gerenciar usuários
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /users:
    get:
      summary: Obter lista de usuários
      description: Retorna todos os usuários cadastrados.
      responses:
        200:
          description: Lista de usuários
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
    post:
      summary: Adicionar novo usuário
      description: Adiciona um novo usuário após validação.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUser'
      responses:
        200:
          description: Usuário adicionado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Usuário adicionado com sucesso."
        400:
          description: Dados inválidos
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                    example: "Dados inválidos"
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: "Campo obrigatório faltando"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
    NewUser:
      type: object
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "johndoe@example.com"
        password:
          type: string
          example: "securePassword123"
      required:
        - name
        - email
        - password

